"""initial

Revision ID: 25aa38d3ab85
Revises: 
Create Date: 2022-04-13 14:08:36.379201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25aa38d3ab85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = postgresql.ENUM('super_admin', 'admin', 'user', name = "user_role")
    user_role.create(op.get_bind())
    op.add_column('user', sa.Column('user_role', sa.Enum('superadmin', 'admin', 'user', name='user_role'), server_default='user', nullable=True))
    op.drop_index('ix_user_perfil', table_name='user')
    op.create_index(op.f('ix_user_user_role'), 'user', ['user_role'], unique=False)
    op.drop_column('user', 'perfil')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('perfil', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_user_role'), table_name='user')
    op.create_index('ix_user_perfil', 'user', ['perfil'], unique=False)
    op.drop_column('user', 'user_role')
    # ### end Alembic commands ###
